### ISSUE TITLE
Notification when stock up or down

### ISSUE THREAD

**Issue by iboen** [iboen/shawk#11]

**Comment by tembem** [comment]
Patokannya apa ya **up** atau **down**? Susah kek-nya haha.

Kalau diganti jadi **Notification when new stock is added** gimana? Jadi sekarang kalau tambah stock baru, langsung muncul dibawah, tidak ada notifikasi apa-apa. Daripada pake toast, sekarang coba pakai notification via firebase. Gimana?

**Comment by tembem** [comment]
Reissue #15
